import type { Project, Task } from './types';

// This file contains the sample data that will be used to seed the database.
// Note: The structure of this data should match the `Project` and `Task` interfaces in `types.ts`.

export const projects: Omit<Project, 'id'>[] = [
  {
    No: 1,
    ProjectName: 'Website Redesign',
    StartDate: '2024-08-01',
    EndDate: '2024-09-30',
    Duration: 61,
    CompletedCount: 1,
    PendingCount: 3,
    Status: 'กำลังดำเนินการ',
  },
  {
    No: 2,
    ProjectName: 'Mobile App Launch',
    StartDate: '2024-08-05',
    EndDate: '2024-10-15',
    Duration: 72,
    CompletedCount: 1,
    PendingCount: 3,
    Status: 'กำลังดำเนินการ',
  },
  {
    No: 3,
    ProjectName: 'Q3 Marketing Campaign',
    StartDate: '2024-07-15',
    EndDate: '2024-09-30',
    Duration: 78,
    CompletedCount: 1,
    PendingCount: 2,
    Status: 'กำลังดำเนินการ',
  },
  {
    No: 4,
    ProjectName: 'API Integration',
    StartDate: '2024-08-10',
    EndDate: '2024-09-20',
    Duration: 42,
    CompletedCount: 0,
    PendingCount: 1,
    Status: 'กำลังดำเนินการ',
  },
];

export const tasks: Omit<Task, 'id'>[] = [
  // Tasks for Website Redesign (proj-1)
  {
    No: 1,
    ProjectName: 'Website Redesign',
    Category: 'Design',
    TaskName: 'Design new homepage mockups',
    Assignee: 'Alice',
    StartDate: '2024-08-01',
    EndDate: '2024-08-15',
    Duration: 15,
    Status: 'จบงานแล้ว',
    Owner: 'Project Manager',
    ProjectType: 'Main',
    User: 'Design Team',
    Want: 'High-fidelity mockups',
    LastUpdateDate: '2024-08-14',
    Effect: 5,
    Effort: 4,
    projectId: 'proj-1',
  },
  {
    No: 2,
    ProjectName: 'Website Redesign',
    Category: 'Development',
    TaskName: 'Develop front-end components',
    Assignee: 'Bob',
    StartDate: '2024-08-16',
    EndDate: '2024-09-01',
    Duration: 17,
    Status: 'กำลังดำเนินการ',
    Owner: 'Project Manager',
    ProjectType: 'Main',
    User: 'Dev Team',
    Want: 'Reusable React components',
    LastUpdateDate: '2024-08-20',
    Effect: 5,
    Effort: 5,
    projectId: 'proj-1',
  },
  {
    No: 3,
    ProjectName: 'Website Redesign',
    Category: 'Development',
    TaskName: 'Setup CMS for the blog section',
    Assignee: 'Charlie',
    StartDate: '2024-09-02',
    EndDate: '2024-09-10',
    Duration: 9,
    Status: 'กำลังดำเนินการ',
    Owner: 'Project Manager',
    ProjectType: 'Fillin',
    User: 'Dev Team',
    Want: 'Headless CMS integration',
    LastUpdateDate: '2024-08-20',
    Effect: 4,
    Effort: 3,
    projectId: 'proj-1',
  },
    {
    No: 11,
    ProjectName: 'Website Redesign',
    Category: 'QA',
    TaskName: 'User testing for new design',
    Assignee: 'Diana',
    StartDate: '2024-09-11',
    EndDate: '2024-09-20',
    Duration: 10,
    Status: 'กำลังดำเนินการ',
    Owner: 'Project Manager',
    ProjectType: 'QuickWin',
    User: 'QA Team',
    Want: 'Usability feedback report',
    LastUpdateDate: '2024-08-20',
    Effect: 5,
    Effort: 3,
    projectId: 'proj-1',
  },

  // Tasks for Mobile App Launch (proj-2)
  {
    No: 4,
    ProjectName: 'Mobile App Launch',
    Category: 'Design',
    TaskName: 'Finalize app UI/UX',
    Assignee: 'Alice',
    StartDate: '2024-08-05',
    EndDate: '2024-08-10',
    Duration: 6,
    Status: 'จบงานแล้ว',
    Owner: 'Project Manager',
    ProjectType: 'Main',
    User: 'Design Team',
    Want: 'Finalized Figma designs',
    LastUpdateDate: '2024-08-09',
    Effect: 5,
    Effort: 4,
    projectId: 'proj-2',
  },
  {
    No: 5,
    ProjectName: 'Mobile App Launch',
    Category: 'Development',
    TaskName: 'Build user authentication flow',
    Assignee: 'Bob',
    StartDate: '2024-08-11',
    EndDate: '2024-08-25',
    Duration: 15,
    Status: 'กำลังดำเนินการ',
    Owner: 'Project Manager',
    ProjectType: 'Main',
    User: 'Dev Team',
    Want: 'Secure login and registration',
    LastUpdateDate: '2024-08-20',
    Effect: 5,
    Effort: 4,
    projectId: 'proj-2',
  },
  {
    No: 6,
    ProjectName: 'Mobile App Launch',
    Category: 'Development',
    TaskName: 'Implement push notifications',
    Assignee: 'Charlie',
    StartDate: '2024-08-26',
    EndDate: '2024-09-05',
    Duration: 11,
    Status: 'กำลังดำเนินการ',
    Owner: 'Project Manager',
    ProjectType: 'QuickWin',
    User: 'Dev Team',
    Want: 'Firebase Cloud Messaging setup',
    LastUpdateDate: '2024-08-20',
    Effect: 4,
    Effort: 2,
    projectId: 'proj-2',
  },
    {
    No: 12,
    ProjectName: 'Mobile App Launch',
    Category: 'Deployment',
    TaskName: 'Prepare App Store submission',
    Assignee: 'Diana',
    StartDate: '2024-09-15',
    EndDate: '2024-09-25',
    Duration: 11,
    Status: 'กำลังดำเนินการ',
    Owner: 'Project Manager',
    ProjectType: 'Main',
    User: 'Release Team',
    Want: 'App Store Connect and Google Play Console setup',
    LastUpdateDate: '2024-08-20',
    Effect: 5,
    Effort: 2,
    projectId: 'proj-2',
  },

  // Tasks for Q3 Marketing Campaign (proj-3)
  {
    No: 7,
    ProjectName: 'Q3 Marketing Campaign',
    Category: 'Planning',
    TaskName: 'Define campaign KPIs',
    Assignee: 'Eve',
    StartDate: '2024-07-15',
    EndDate: '2024-08-01',
    Duration: 18,
    Status: 'จบงานแล้ว',
    Owner: 'Marketing Head',
    ProjectType: 'Main',
    User: 'Marketing Team',
    Want: 'Clear success metrics',
    LastUpdateDate: '2024-07-30',
    Effect: 4,
    Effort: 1,
    projectId: 'proj-3',
  },
  {
    No: 8,
    ProjectName: 'Q3 Marketing Campaign',
    Category: 'Content',
    TaskName: 'Create social media content calendar',
    Assignee: 'Frank',
    StartDate: '2024-08-02',
    EndDate: '2024-08-20',
    Duration: 19,
    Status: 'กำลังดำเนินการ',
    Owner: 'Marketing Head',
    ProjectType: 'Fillin',
    User: 'Marketing Team',
    Want: 'Month-long content schedule',
    LastUpdateDate: '2024-08-20',
    Effect: 3,
    Effort: 3,
    projectId: 'proj-3',
  },
   {
    No: 9,
    ProjectName: 'Q3 Marketing Campaign',
    Category: 'Execution',
    TaskName: 'Launch email marketing sequence',
    Assignee: 'Grace',
    StartDate: '2024-08-21',
    EndDate: '2024-09-01',
    Duration: 12,
    Status: 'กำลังดำเนินการ',
    Owner: 'Marketing Head',
    ProjectType: 'QuickWin',
    User: 'Marketing Team',
    Want: 'Drip campaign for new leads',
    LastUpdateDate: '2024-08-20',
    Effect: 4,
    Effort: 2,
    projectId: 'proj-3',
  },

  // Task for API Integration (proj-4)
  {
    No: 10,
    ProjectName: 'API Integration',
    Category: 'Research',
    TaskName: 'Research payment gateway APIs',
    Assignee: 'Heidi',
    StartDate: '2024-08-10',
    EndDate: '2024-08-18',
    Duration: 9,
    Status: 'กำลังดำเนินการ',
    Owner: 'Tech Lead',
    ProjectType: 'Main',
    User: 'Dev Team',
    Want: 'Comparison of Stripe, Braintree, and Adyen',
    LastUpdateDate: '2024-08-15',
    Effect: 5,
    Effort: 2,
    projectId: 'proj-4',
  },
];
